source 'https://www.rubygems.org'

gem 'allure-cucumber','2.13.6'
gem 'capybara', '~>3.30'
gem 'chromedriver-helper'
gem 'client-api'
gem 'cucumber'
gem 'java-properties'
gem 'json'
gem 'log4r'
gem 'parallel_tests'
gem 'pry'
gem 'rake'
gem 'remote_ruby'
gem 'require_all'
gem 'rest-client'
gem 'rspec'
gem 'selenium-webdriver', '~> 3.142.0'
gem 'site_prism'
gem 'time_difference', '~> 0.7.0'
gem 'singleton'
gem 'forwardable'
gem 'gmail'
